
version: 2

models:
  - name: int_companies_avg_past_employees_lifespan
    description: "Companies with average time employees stay there"
    columns:
      - name: employee_urn
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
